### ISSUE TITLE
Question about a bunch of slashes at the end of the URL

### ISSUE THREAD

**Issue by Zickerman** [illuminatech/url-trailing-slash#15]
Hi, is there any way to configure this library to prevent placing more than 1 forward slash, without using additional Laravel middleware?

I took an example:
`Route::get('items/', ItemController::class.'@index')->name('items.index');
`

And I get:
echo route('items.index'); //output: 'http://example.com/items/'

It's ok, but if someone puts a few more slashes in the URL:
http://example.com/items///////

It will work but it's not correct

| This Package Version      | 1.1.11
| Laravel Framework Version | 8.40
| PHP version               |  8.0

**Comment by klimov-paul** [comment]
Resolved by commit 1f398a24bb0054c39f983f71d6a64b12531931ae
