### ISSUE TITLE
Not working with cache

### ISSUE THREAD

**Issue by interposition** [illuminatech/url-trailing-slash#4]
### What steps will reproduce the problem?
Call artisan route:cache
Generate or resolve route with end  slash.
### What is the expected result?
Generated or resolved route has end slash.
### What do you get instead?
Generated or resolved route has't end slash.
### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.1.3
| Laravel Framework Version | 7.2.1
| PHP version               |  7.3/7.4
| Operating system          |

**Comment by klimov-paul** [comment]
Indeed the route caching is broken for the latest Laravel version, as route caching has been reworked introducing `CompiledRouteCollection`.

**Comment by klimov-paul** [comment]
Issue affects Laravel version >= 7.0.0.
For the older versions caching works correctly.

**Comment by klimov-paul** [comment]
PR https://github.com/laravel/framework/pull/32416 has been merged.
Once this chnageset appear in new Laravel Framework stable release the problem will be solved.

**Comment by klimov-paul** [comment]
Preparation changeset: 7acdbd75a6374095ee4a707bcc17f80f31685b9d

**Comment by klimov-paul** [comment]
Released: https://github.com/illuminatech/url-trailing-slash/releases/tag/1.1.4
