### ISSUE TITLE
lumen support?

### ISSUE THREAD

**Issue by 8ctopus** [illuminatech/url-trailing-slash#5]
Thanks for a great plugin!
Does it support lumen? I'm trying to use it but get:

```
Argument 1 passed to Illuminatech\UrlTrailingSlash\RoutingServiceProvider::Illuminatech\UrlTrailingSlash\{closure}() must be an instance of Illuminate\Routing\UrlGenerator, instance of Laravel\Lumen\Routing\UrlGenerator given, called in /var/www/site/gateway-new/vendor/illuminate/container/Container.php on line 696 (View: /var/www/site/gateway-new/resources/views/assets.blade.php) (View: /var/www/site/gateway-new/resources/views/assets.blade.php)
```

**Comment by klimov-paul** [comment]
It is obvious from the error, you have posted, that Lumen does not use "illuminate/routing" package, providing its own routing system instead.
This extension relies on "illuminate/routing", enhancing it. So it will not function for the Lumen.

You may attempt to integrate "illuminate/routing" into Lumen application replacing its original routing, but I can not say if it is possible.

**Comment by 8ctopus** [comment]
@klimov-paul thanks for the reply and for your time. Sorry it wasn't obvious for the layman I am.
