### ISSUE TITLE
Caching routes breaks trailing slashes

### ISSUE THREAD

**Issue by rreynier** [illuminatech/url-trailing-slash#6]
### What steps will reproduce the problem?
- create a route with trailing slash: `Route::get('/blog/', 'BlogController@index')->name('blog.index');`
- create route cache: `php artisan route:cache`
- use route() method to get a url: `route('blog.index')` 

### What is the expected result?
`https://mywebsite.com/blog/`

### What do you get instead?
`https://mywebsite.com/blog`

### Additional info

This likely relates to https://github.com/illuminatech/url-trailing-slash/issues/4

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.1.4
| Laravel Framework Version | 7.16.1
| PHP version               | 7.4

**Comment by klimov-paul** [comment]
Resolved via #6

**Comment by rreynier** [comment]
Thank you!

**Comment by rreynier** [comment]
I assume you will be tagging a release for this?
