### ISSUE TITLE
UrlGenerator does not work for generating verificationUrl

### ISSUE THREAD

**Issue by oheck** [illuminatech/url-trailing-slash#8]
### What steps will reproduce the problem?

1. Enable verification `Auth::routes(['verify' => true]);`
2. Try to register

### What is the expected result?
Registration should work and verificationUrl should get generated.

### What do you get instead?
An error in src/Illuminate/Routing/UrlGenerator.php for `$key = call_user_func($this->keyResolver);`.

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.0.1
| Laravel Framework Version | 5.8.38
| PHP version               | 7.4
| Operating system          | Mac

**Comment by oheck** [comment]
#9 PR here.

**Comment by klimov-paul** [comment]
Resolved by commit 954715754cc5fe0e85c70ef0af1b9f6a97c43471
